AddonId: Nintendo
Packages:
  - Version: 1.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-07
    PackageUrl: https://github.com/XenorPLxx/playnite-library-nintendo/releases/download/1.2/NintendoLibrary_1_2.pext
    Changelog:
      - Fixed cookie removal for reauthentication
  - Version: 1.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-07
    PackageUrl: https://github.com/XenorPLxx/playnite-library-nintendo/releases/download/1.1/NintendoLibrary_1_1.pext
    Changelog:
      - Added list filtration based on content type
  - Version: 1.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-06
    PackageUrl: https://github.com/XenorPLxx/playnite-library-nintendo/releases/download/1.0/NintendoLibrary_1_0.pext
    Changelog:
      - Playnite 9 support
      - Added Nintendo authentication
      - Added download of digital Nintendo purchases
